name: 'Dungeons & Drunk Dragons'
favicon: null
layout_spectrum: 0.01027265447191894
typography_spectrum: 0.35046793543733656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8663587381597608
  lightness: 0.35566170676611364
  saturation: 0.6412981285247952
  rhythmicContrast: 0.6716981895733625
purpose: []
